name: Setup Python with UV
description: Install UV, setup Python

inputs:
  all-extras:
    description: "Install all optional dependencies"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Setup Python
      run: uv python install
      shell: pwsh